### ISSUE TITLE
Reintroduce support for playlists, live streams, ect

### ISSUE THREAD

**Issue by DrKain** [DrKain/scrape-youtube#11]
Support will need to be added to search for channels, playlists, movies and live streams.  
Each type should have their own interface in the [interfaces file](https://github.com/DrKain/scrape-youtube/blob/1f69e2d151df20de5cf39079d7649acb177de39a/src/interface.ts), Extending the default [Result](https://github.com/DrKain/scrape-youtube/blob/1f69e2d151df20de5cf39079d7649acb177de39a/src/interface.ts#L31-L39) interface when needed.  

#### Channels  
- name  
- link  
- verified  
    - If the channel has a verified badge  
- thumbnail

#### Live Streams  
- watching  
    - Number of users watching the stream  
- duration  
    - How long (in seconds) the stream has been running for  

#### Playlists  
- videoCount  
    - The number of videos in the playlist  
- videos  
    - An array of videos in the playlist. If possible the [Video](https://github.com/DrKain/scrape-youtube/blob/1f69e2d151df20de5cf39079d7649acb177de39a/src/interface.ts#L45) interface should be used.  

#### Movies  
These are just the [Result](https://github.com/DrKain/scrape-youtube/blob/1f69e2d151df20de5cf39079d7649acb177de39a/src/interface.ts#L31) interface, but the channel data should be static. All YouTube movies have the same channel information.  
  
#### Progress:  
- [x] Channels   
- [x] Playlists  
- [x] Live Streams  
- [x] Movies

**Comment by tycrek** [comment]
Just found this after realizing the office V3 API only lets me do 100 search requests per day. If I get a chance I'll see if I can be of any help

**Comment by DrKain** [comment]
@tycrek Just released an update changing and optimizing everything, The remaining types should now be relatively simple to add if you still wanted to take a look.
   
If not I'll be back to my computer in a few days, then I'll probably add them in.

**Comment by DrKain** [comment]
As a side note I see you use it in [mandatum](https://github.com/tycrek/mandatum). A YouTube update broke the old version so you may need to update

**Comment by tycrek** [comment]
> 
> 
> As a side note I see you use it in [mandatum](https://github.com/tycrek/mandatum). A YouTube update broke the old version so you may need to update

Thank you for letting me know!
