### ISSUE TITLE
URL Support

### ISSUE THREAD

**Issue by hansputera** [DrKain/scrape-youtube#13]
**Is your feature request related to a problem? Please describe.**

 I'm always frustrated when i add the url in query

**Describe the solution you'd like**
Add URL support for query, so someone can search the video from url.

**Comment by DrKain** [comment]
It sounds like you should look into [ytdl-core](https://www.npmjs.com/package/ytdl-core#ytdlvalidateurlurl). You can use `validateURL` to check if the query is a valid youtube URL then fetch the video information. If it is not, simply pass the query to scrape-youtube.   
This will allow you to "search the video from url"

> `ytdl.validateURL(url)`
> Returns true if able to parse out a valid video ID.  
  
> ` ytdl.getInfo(url, [options])`
> Gets metainfo from a video. Includes additional formats, and ready to download deciphered URL. This is what the ytdl() function uses internally.

**Comment by hansputera** [comment]
why you don;t make that feature in scrape-youtube?

**Comment by DrKain** [comment]
Added in bfe6fae. It's probably overkill but there you go.
