### ISSUE TITLE
[Question] Fetching Video ID

### ISSUE THREAD

**Issue by IGRohan** [DrKain/scrape-youtube#17]
is there any way to fetch the video id of the first result? i JUST wanna log the ID of the first video result

**Comment by DrKain** [comment]
```javascript  
import youtube from 'scrape-youtube';

youtube.search('Gloomy Sunday').then((results) => {
    console.log(results.videos[0].link);
    // https://youtu.be/55FP1LfkkVQ
});
```

**Comment by DrKain** [comment]
If you have any more questions please check the [README](https://github.com/DrKain/scrape-youtube/blob/master/README.md) first
