### ISSUE TITLE
Search erroring out

### ISSUE THREAD

**Issue by VlaDexa** [DrKain/scrape-youtube#19]
**Describe the bug**
Every time I want to search something, it just says: 'Failed to extract video data. The request may have been blocked'

**To Reproduce**
Just do any search with any string

**Versions:**
 - Package: 1.1.0 or 2.0.1
 - Node: lts

**Comment by DrKain** [comment]
Fixed in https://github.com/DrKain/scrape-youtube/commit/e43ddea206ed176bc300da083d86d439ece72ed8
