### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by viramaham73** [DrKain/scrape-youtube#25]
hi
thanks for this source code
how use proxy if blocket my ip?

**Comment by DrKain** [comment]
As mentioned in the [readme](https://github.com/DrKain/scrape-youtube#custom-request-options) you can pass [custom request options](https://nodejs.org/api/http.html#http_http_request_options_callback)  
  
```javascript   
const options = {
    requestOptions: {
        host: 'some.proxy.com',
        port: 8080
    }
};

youtube.search('Poets of the fall', options);
```

**Comment by viramaham73** [comment]
thanks😘

**Comment by viramaham73** [comment]
hi
set value but i have error
(node:34540) UnhandledPromiseRejectionWarning: Error: Client network socket
disconnected before secure TLS connection was established

**Comment by DrKain** [comment]
That's an issue with whatever proxy you're using, not this package.

**Comment by viramaham73** [comment]
thanks . create custom proxy in my server and test with chrome and firefox .
but set in requestoprions show this error =

(node:53411) UnhandledPromiseRejectionWarning: Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
(node:53411) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:53411) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
please help me

**Comment by DrKain** [comment]
ECONNREFUSED means it couldn't connect to your proxy server.
