### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by DragosDAS** [DrKain/scrape-youtube#26]
**Is your feature request related to a problem? Please describe.**
Apparently the json I'm getting now is in Ukrainian and I don't know if I can change it to English

**Describe the solution you'd like**
Changing the language according to preferences

**Additional context**

**Comment by DrKain** [comment]
As mentioned in the [README](https://github.com/DrKain/scrape-youtube#custom-request-options) you can specify a custom language. If it's getting Ukrainian results that's probably the location of the server running the bot.
   
```javascript  
youtube.search('Poets of the fall', {
    requestOptions: {
        headers: { 'Accept-Language': 'en' }
    }
});
```
