### ISSUE TITLE
No results for many short terms

### ISSUE THREAD

**Issue by accessTechnology** [DrKain/scrape-youtube#31]
These terms are failing regularly on my app;

'cat'
'cats'
'hey duggee'
'duggee'
'kids toys play'
'toys'
'roblox'
'lego'

Any idea would these might fail, yet most requests work fine?

**Comment by DrKain** [comment]
Please use the correct bug report template. Edit your issue with the required information and then I can provide the help you want.

**Comment by DrKain** [comment]
This might be fixed in #32 (v2.0.8) or #30 (v2.0.9) but seeing as you thought it was a good idea to delete the bug report template I can't be sure.
