### ISSUE TITLE
No results for certain short search terms

### ISSUE THREAD

**Issue by accesstechnology-mike** [DrKain/scrape-youtube#33]
**Describe the bug**
On a UK located server, the search term 'duggee' doesn't pull through any results. (same issue for many other terms, lego, cats, 'kids toys play' )

note: safesearch is enabled through the header options: { Cookie: "PREF=f2=8000000" }

**To Reproduce**
1. On UK server, search 'duggee'
2. No returned results available

**Expected behavior**
Duggee should pull through the 20 results listed here: https://www.youtube.com/results?search_query=duggee

![image](https://user-images.githubusercontent.com/55278705/106736040-dd195e00-660c-11eb-84bc-7e6cbf2652e2.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/55278705/106736094-edc9d400-660c-11eb-8002-dd743326b774.png)

**Versions:**
 - Package: 0.2.6
 - Node: 12.20.1

**Additional context**
'duggee' results pull through on a machine located in Pakistan.

**Comment by DrKain** [comment]
Update the package to 2.0.9 and see if the problem persists

**Comment by accessTechnology** [comment]
> > Package: 0.2.6
> 
> I assume you mean 2.0.6. Update the package to 2.0.9 and see if the problem persists, there have been several updates that could be related

Not a typo! Didn't realise is was so out of date. Will update app to latest version and report back.

**Comment by accesstechnology-mike** [comment]
updated to latest v2.0.9. Problem still persists unfortunately. 

![image](https://user-images.githubusercontent.com/55278705/106815796-47adb680-666c-11eb-9896-4e204f61a74a.png)

For reference, most other searches are working fine:

![image](https://user-images.githubusercontent.com/55278705/106816059-b7bc3c80-666c-11eb-8919-56b6b24d8935.png)

'duggee' never works, 'lego' is intermittent

**Comment by DrKain** [comment]
Alright thanks for reporting. I ran a few tests on a server I have in London and wasn't able to reproduce the issue you're having.  
I'll need to dig around more during the weekend. If you could provide a sample of the code (showing how you're using the package, filtering the results ect) that would be helpful.

**Comment by accesstechnology-mike** [comment]
I'm sorry. I'm not used to node and forgot to actually re-build the app
once it was updated.

It does seem to fine now on latest version. Thanks for helping me out.

**Comment by accesstechnology-mike** [comment]
Hi,  this is happening again on 2.0.9:

![image](https://user-images.githubusercontent.com/55278705/107258929-4d244b80-6a34-11eb-9226-5e9bbfb4e2f2.png)

**Comment by accesstechnology-mike** [comment]
Code here:

```
const express = require("express");
const { default: youtube } = require("scrape-youtube");

const cache = require("../helpers/cache");

const Router = express.Router();

Router.get("/search", async (req, res) => {
  try {
    let { q, cached } = req.query;
    const allowCached = cached !== "false";
    if (!q) return res.send({ error: "Invalid query!" });
    q = q.trim();
    if (allowCached) {
      const cachedResults = await cache.getResults(q);
      if (cachedResults && cachedResults.length !== 0) {
        return res.send({ results: cachedResults, cached: true });
      }
    }
    let freshResults = await youtube.search(
      q,
      { safeSearch: true },
      { safeSearch: true, headers: { Cookie: "PREF=f2=8000000" } }
    );
    freshResults = freshResults.videos.map((video) => ({
      id: video.id,
      title: video.title,
    }));
    res.send({ results: freshResults, length: freshResults.length });
    if (freshResults.length > 0) await cache.saveResults(q, freshResults);
  } catch (error) {
    console.error(error);
    res.send({ error: "Backend error." });
  }
});

module.exports = Router;

```

**Comment by accesstechnology-mike** [comment]
![image](https://user-images.githubusercontent.com/55278705/107259289-ba37e100-6a34-11eb-8975-27adf16b78f9.png)
cats / lego and both intermittent too
