### ISSUE TITLE
Get the ID of a youtube channel

### ISSUE THREAD

**Issue by ExpErgio** [DrKain/scrape-youtube#38]
Hello. I'm writing here because I don't know exactly where to do it.

I'm trying to find a way to get the ID of a YouTube channel, through your "npm".

I know that your "npm" is used to obtain the information of the videos, streams, and playlists of a youtube channel, but I don't know if it is possible to get this type of information

**Comment by DrKain** [comment]
By default not possible with this package. Channels often have custom URLs when using the search so that's what's in the response.  
A package like ytdl-core can fetch channel IDs (along with other information) when fed a Video URL

**Comment by DrKain** [comment]
YouTube changed how navigation is managed so this is now possible.

Added in abfa3822459838ffc6b870702b92c9498564f6ac  -> `video.channel.id`
