### ISSUE TITLE
Invalid JSON returned on empty searches where itemSectionRenderer does not exist

### ISSUE THREAD

**Issue by MattieTK** [DrKain/scrape-youtube#39]
**Describe the bug**
Hi there,

This seems to happen when no results are returned:
eg. https://www.youtube.com/results?search_query=Benzinga+Live&sp=EgJAAQ%253D%253D

**To Reproduce**
1. Make a search for which no results are returned
2. See the error `TypeError: Cannot read property 'itemSectionRenderer' of undefined`

**Expected behavior**
The search should return empty

**Screenshots**
The Bezinga search is the one that isn't returning at this time, and this is where the error is thrown.
![image](https://user-images.githubusercontent.com/125273/117740840-317a3e00-b1f9-11eb-95ca-b7e494f48ba3.png)

**Versions:**
 - Package: 2.1.3
 - Node: 14.16

**Additional context**
I guess youtube changed their styling 😢

**Comment by DrKain** [comment]
Thanks for reporting. I'll take a look at this shortly

**Comment by DrKain** [comment]
Should be fixed in 2.1.4
