### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Skidamek** [DrKain/scrape-youtube#50]
In lastest (2.1.10) version "search" function not working, when i install earlier version (2.1.9) it work

**Comment by Skidamek** [comment]
I using discord.js in version 13.2.0, javascript and node.js in version 16.13.0

**Comment by DrKain** [comment]
Please fill in the issue template properly, then I can take a look at the issue

**Comment by DrKain** [comment]
Considering the only change between those version was the removal of the default import, you probably need to change  

```js
const youtube = require('scrape-youtube').default;
```
to
```js
const youtube = require('scrape-youtube').youtube;
```

**Comment by Skidamek** [comment]
oh it work, thx

**Comment by DrKain** [comment]
Because this is getting confusing for people, from 2.1.11 and up you can just use 

```js
import { youtube } from 'scrape-youtube';
// or 
const youtube = require('scrape-youtube');
```
