### ISSUE TITLE
TypeError when using exported search function

### ISSUE THREAD

**Issue by CosmosisT** [DrKain/scrape-youtube#51]
```js
const youtube = require('scrape-youtube');
```

Perhaps obvious but youtube.search is no longer a function this way; any means of updating the example to help others understand I do enjoy this quite a bit! :)

```js
const youtube = require('scrape-youtube').youtube;
youtube.search("hello-world").then((results) => {
    console.log(results);
});
```

**Comment by DrKain** [comment]
Thanks for reporting. This was a mistake in the code, the example should work find in 2.1.13

**Comment by CosmosisT** [comment]
Perfect! Was just updating and noticed that immediately, works like a charm. :)
