### ISSUE TITLE
Filter videos by hashtag

### ISSUE THREAD

**Issue by jinseok9338** [DrKain/scrape-youtube#54]
I know that you can filter whether the video is live or not and so on but it will be helpful to add features to filter only shorts too. 

it will be easy since the shorts video has shorts in their url

**Comment by DrKain** [comment]
What are shorts? I've not heard of this before. If you're referring to the video duration YouTube only has a few filters for these:

| Duration  | Custom SP |
| ------------- | ------------- |
| under 4 minutes  | EgIYAQ%253D%253D  |
| 4-20 minutes  | EgIYAw%253D%253D  |
| over 20 minutes | EgIYAg%253D%253D |

**Comment by DrKain** [comment]
After digging around it looks like you're talking about YouTube hashtags. You can simply add `"#shorts"` to the end of any search query. The results will be videos under 1 minute with `#shorts` in the title.  
  
The quotes are required for a strict search. Example:  
  
```js
youtube.search('anime "#shorts"', options).then(console.log);
```

**Comment by DrKain** [comment]
Unfortunately there's no YouTube filter for these, nor is there any identifiable information in the render data. As far as I'm aware there's no reliable method of searching videos by hashtag either, so such a 'type' filter is not possible right now.
