### ISSUE TITLE
Country filter

### ISSUE THREAD

**Issue by Manojyadavmy10** [DrKain/scrape-youtube#61]
How to apply country filter for search query so that it will returns videos of that particular country

**Comment by DrKain** [comment]
YouTube is unreliable when it comes to filtering by country and you're very limited on what information is gained from scraping. The two best options would be setting the `Accept-Language` header and/or [using a proxy server](https://nodejs.org/api/http.html#http_http_request_options_callback) for all searches targeting a certain country.
