### ISSUE TITLE
Can I search by channel?

### ISSUE THREAD

**Issue by tbobker123** [DrKain/scrape-youtube#62]
I want to use this to scrape all the videos from a channel, but there doesnt seem to be any option to select a channel? Searching using the channel name doesnt return all videos on that channel.

**Comment by DrKain** [comment]
Unfortunately no, these are the only filters available for the search:  

![firefox_2023-01-18_01-45-58](https://user-images.githubusercontent.com/5300315/212902474-d167ad59-102f-4ad9-ba72-cddecb4eb9a9.png)
  
If you'd like to fetch videos for a single channel you may want to look into using the YouTube API
