### ISSUE TITLE
Returns empty array instead of results

### ISSUE THREAD

**Issue by sodiumkid** [DrKain/scrape-youtube#7]
**Describe the bug**
When calling multiple times with any search query, it returns an empty array sometimes. 

**To Reproduce**
1. Try calling the example in readme multiple times

**Comment by DrKain** [comment]
Thanks for reporting this. Hard to pinpoint the cause, Might need some time to find a reliable workaround or fix.  

I notice that the `ytInitialData` script data ([sample](https://pastebin.com/raw/ihMcGpS0)) is always available when results fail to load, this could be probably be used as a fallback or even a replacement.

**Comment by Yimura** [comment]
Can confirm this problem has been occurring a lot lately.

**Comment by DrKain** [comment]
New version **should** be more reliable. Feel free to open another issue or PR a change if you have any problems. I'll look into it when I get the time.
